### ISSUE TITLE
Next release timeline

### ISSUE THREAD

**Issue by u-anurag** [u-anurag/OpenSeesPy#21]
@zhuminjie, please keep us in the loop when you plan to release the next version. We have a lot to add and fix one known issue in plot_modeshape().

**Comment by zhuminjie** [comment]
I think once you are ready you can just go ahead to submit the updates. I don't have a specific time line to release. I very much depend on the updates in OpenSees and the updates you guys make. How about this, when you are ready to have a new release for the plotting functions, just let me know, I can push new releases with plotting and OpenSees in an alternate order.

**Comment by u-anurag** [comment]
Sounds good. Thanks!
