### ISSUE TITLE
Consistent Imports

### ISSUE THREAD

**Issue by cslotboom** [u-anurag/OpenSeesPy#22]
One thing I'm wondering about is the import for OpenSees.
In some places we use import *

`from openseespy.opensees import *`

But for most of our other functions we use _**import as**_

```
import openseespy.opensees as ops

import internal_database_functions as idbf
import internal_plotting_functions as ipltf
```

Personally I like "import openseespy.opensees as ops" because it is explicit, but I think as long as we are consistent it's fine.

**Comment by u-anurag** [comment]
Sure! We can change it at some point. It hasn't caused any problems yet.

**Comment by cslotboom** [comment]
Okay, sounds good! I can roll this out in a upcoming patch.

**Comment by u-anurag** [comment]
I took care of it in the Get_Rendering.py file.
