### ISSUE TITLE
Selective inputs for createODB

### ISSUE THREAD

**Issue by cslotboom** [u-anurag/OpenSeesPy#35]
Things to update:
- [x] Allow the user to select what they want saved by the createODB command.
- [x] Allow the user to record data only at specific time-steps using the createODB command

**Comment by u-anurag** [comment]
I will add selective input for createODB(). I don't think we should have record data at a specific time-step. Users can plot the output at a specific time-step using plot_deformedshape() (and plot_stresses() and plot_elementforce() in future). The createODB() is not supposed to be used for analysis involving a large suite of ground motions. This command is there only to understand the behavior of the structure to help users prepare their strategy for further analysis.

**Comment by cslotboom** [comment]
Okay. I just want to make sure I was clear. I was referring to recording at certain intervals, using the '-dT' flag. For example, your analysis time steps might look something like this:
**Case 1:**
t1 = 0.02
t2 = 0.04
t3 = 0.041
t4 = 0.042
t5 =0.062
t6 = 0.066
t7 = 0.081

We can specify a time interval, say 0.02s, then the recorder only records after that interval has been reached:
**Case 2:**
t1 = 0.02
t2 = 0.04
t3 = 0.062
t4 = 0.081

This cuts down on the data in the file, and smooths the time between time steps. For animations, this is potentially useful, because every frame is given the same delay, regardless of the time-step size. In Case 1, it will appear like the animation is speeding up or slowing down, real time doesn't match animation time. In Case 2 the animation will be relatively smooth.

Either way, I just wanted to make sure I was clear.

**Comment by u-anurag** [comment]
I see what you meant. I'll add that to the command. Thanks for clarifying it.

**Comment by u-anurag** [comment]
I have implemented it.
