### ISSUE TITLE
Create an Output Database 

### ISSUE THREAD

**Issue by u-anurag** [u-anurag/OpenSeesPy#4]
Add procedure to save an Output Database folder with files for node and element data, analysis output such as displacement, drift, element force, base shear, stress and strain.

**Comment by cslotboom** [comment]
For the database folder, are you thinking an OpenSees model database, or text files with the relevant information?
Text files generally may be a little easier for people to work with.

**Comment by u-anurag** [comment]
Just text files with the standard .out extension. See the code I have added to this branch.  https://github.com/u-anurag/OpenSeesPy/commit/cfe84a02d911add5f1d919c2a15c657785a2ef43

**Comment by cslotboom** [comment]
That makes sense. Looks good to me.
If we are always saving all the element stress/strains, the file sizes could become quite large.
How would you feel about:

-  having some functionality to turn on or off certain outputs
-  having an option to save only at certain time steps.
i.e.
```
if ele_forces == True:
    recorder('Element', '-file', EleForceFile, '-dT', deltaT=0.01, '-ele', *eleList, '-dof',*dofList, 'localForce')
``` 

Also, doesn't close on write slow down the saving process significantly? I haven't actually tested this, but I did see a warning on the wiki: https://openseespydoc.readthedocs.io/en/latest/src/nodeRecorder.html
It might be cleaner to let the user issue the wipe command themselves at the end of the analysis.

**Comment by u-anurag** [comment]
* Once we have all the functions working, we'll add options to save data. First, let's finish the basic code.
* You are right about the "close on write" thing. I'll remove it and let the users issue the wipe command.

**Comment by u-anurag** [comment]
This is complete now.
