### ISSUE TITLE
nodeCoord

### ISSUE THREAD

**Issue by cslotboom** [u-anurag/OpenSeesPy#41]
Just a quick check on line 671 of get rendering

Should these "nodeCoord" be "nodeCoords"?
if so, I can correct that in #40 

Also, it appears like there is no "lnode" defined for the plotTri on line 680. Should "lnode" be "inode" in this case?
I can also address that if it is the case

```
if len(Nodes) == 3:
	## 2D Planer three-node shell elements
	iNode = nodeCoord(Nodes[0])
	jNode = nodeCoord(Nodes[1])
	kNode = nodeCoord(Nodes[2])
					
	iNode_final = nodecoordsFinal(Nodes[0])
	jNode_final = nodecoordsFinal(Nodes[1])
	kNode_final = nodecoordsFinal(Nodes[2])

	if overlap == "yes":
		ipltf._plotTri2D(iNode, jNode, kNode, lNode, ax, show_element_tags, eleTag, "wire", fillSurface='no')
					
	ipltf._plotTri2D(iNode_final, jNode_final, kNode_final, lNode_final, ax, show_element_tags, eleTag, "solid", fillSurface='yes')
					
```

**Comment by u-anurag** [comment]
You are right. I need to create a text example for tri elements as well. Thanks for spotting these errors.
