### ISSUE TITLE
Animation function name

### ISSUE THREAD

**Issue by u-anurag** [u-anurag/OpenSeesPy#42]
@cslotboom I was thinking of changing the name of the animation function to `animate_deformedshape()` from `getDispAnimationSlider()`. It keeps the command format in line with plot_deformedshape(). What do you think?

**Comment by cslotboom** [comment]
That makes sense to me, I support that.
Why don't I make that change in the upcoming patch this weekend.

I'm going to confirm everything works, which may involve some general changes to all the functions.
