### ISSUE TITLE
V1 Release: getNodesandElements and getModeShapeData

### ISSUE THREAD

**Issue by cslotboom** [u-anurag/OpenSeesPy#44]
I'm wondering if these functions should be moved to get_rendering.
In theory users will have/want access to these.

I can address if so.

**Comment by cslotboom** [comment]
Re-evaluating, I think these functions are probably okay where they are. Changing them makes messes up the imports a lot.
I consider this closed unless anyone else has comments.

**Comment by u-anurag** [comment]
All the data saving should be through the `createODB()` command for now. Unless there is a critical requirement of introducing a new function.

**Comment by cslotboom** [comment]
Makes sense to me.
