### ISSUE TITLE
Independently Running Test Suite

### ISSUE THREAD

**Issue by cslotboom** [u-anurag/OpenSeesPy#48]
@u-anurag 
Before we make any commits to the main, it would be good if you could try to run the "RunTests.py" file, and confirm that all tests return okay in your environment.

**Comment by u-anurag** [comment]
I get failed tests. For one, `TestModel_ODB\Nodes.out not found`. It did not create an Output database for me.

**Comment by cslotboom** [comment]
Oh shoot - so this test is an older test. I manually created a database and tried to read from it, but it looks like I deleted that database when preparing the files for upload.

We honestly could remove that test, or commented it out for now. We have newer, more sophisticated examples that test the same thing on a real model.

**Comment by u-anurag** [comment]
That is what I was thinking of. We could just use simple examples to run through pytest. Could you go ahead and comment it out for now. We are done with everything else for this 1st milestone. Once you are done, I'll push it to the official repo.

**Comment by u-anurag** [comment]
I did that. Don't worry about it.
