### ISSUE TITLE
Follow up About Function Input Arguements

### ISSUE THREAD

**Issue by cslotboom** [u-anurag/OpenSeesPy#53]
I'm following up our conversation about function arguments here for clarity

> You are right about confusing the users on optional arguments. My idea was to use Model="model" and LoadCase="loadcase" format everywhere, similar to other commands. This is only for these two arguments. This is also being followed in the plot_deformedshape() command. What do you suggest?

I think one thing we can be consistent on is the order of the arguments. Some functions need to know the database, i.e. **plot_deformedshape**, **animate_deformedshape**, and some don't, i.e. **plot_model**

For the functions that need the database, we could use regular arguments. i.e. 
`plot_deformedshape(Model, LoadCase, ....)`

For the functions that don't need the database, we could use keyword arguments.
`plot_model(Model="model", LoadCase="loadcase", ....)`

But for all functions, we use the same ordering. That way the user always has the expectation that the first two arguments refer to the model, and it's clear what arguments they need to pass. 

If we need to ensure backwards compatibility with plot_model, we could introduce some error handling.

**Comment by u-anurag** [comment]
The reason for having Model="modelName" at the end of plot_model() command is that the command works without and with an output database. This optional argument should be towards the end of all the inputs. Same goes for plot_modeshape(). Other commands such as plot_deformedshape() and animate_deformedshape() can not work without Model="modelName" and LoadCase="loadcaseName" and that is why they should be at the beginning of the arguments. It conveys the priority of these inputs.

**Comment by cslotboom** [comment]
Okay. I still think it would make more sense for the user if the input arguments were in the same order for all functions, but it's a small detail.

I would argue that we should use regular arguments instead of keyword arguments (i.e. **Model** instead of **Model  = 'model'**) for functions where the model is mandatory.
Right now we use error handling, which seems a little counter intuitive.

I think at some-point we will probably want to move to a more objected orientated approach with our plots, we can probably revisit this then if necessary.
I'm happy to close this for now.
