### ISSUE TITLE
animation output

### ISSUE THREAD

**Issue by u-anurag** [u-anurag/OpenSeesPy#54]
@cslotboom I ran animate_deformedshape() in cmd and did not see any animation. Only got the following output.

![image](https://user-images.githubusercontent.com/35711550/86858693-66b87b80-c07e-11ea-9721-3193185f4fe2.png)

**Comment by cslotboom** [comment]
Did you return the animation object? The animation command must return an object to be active for whatever reason.

`animate_deformedshape(args) `
does not show anything

`ani = animate_deformedshape(args) `
shows the animation

Let me know if that solved, otherwise I will investigate further.

**Comment by cslotboom** [comment]
Regardless of if this was your problem, it's probably a good idea to make this really clear in the documentation, I can see this tripping a lot of people up...

**Comment by u-anurag** [comment]
No, I did not return any object. However, I added `plt.show()` at the end of the `animate_deformedshape()` and it worked. Is there any problem with using plt.show()?

**Comment by cslotboom** [comment]
I don't see any immediate problem with that. No guarantees, but if it's working, it's probably okay.

If this is the approved approach, `plt.show()` should probably be added to **animate_fibreResponse2** as well.

**Comment by u-anurag** [comment]
I have added that. See #55.

**Comment by u-anurag** [comment]
It is working with cmd and in Jupyter Notebooks.

**Comment by cslotboom** [comment]
Good to hear!

**Comment by u-anurag** [comment]
Is it possible to display "time" in the animation plot? Similar to step number shown. 

![image](https://user-images.githubusercontent.com/35711550/86946333-7334e680-c107-11ea-9c12-83ddaa92edb8.png)

**Comment by cslotboom** [comment]
I think it is possible. I can take a look over the next few days.

**Comment by u-anurag** [comment]
For now, I put the time stamp as a text on the screen. Check out the latest code before you change anything and try to run an example.

**Comment by cslotboom** [comment]
Okay. I have found a way of converting the slider from frames to timesteps, I'll take a look then make the change later tonight.
