### ISSUE TITLE
Update Animation

### ISSUE THREAD

**Issue by cslotboom** [u-anurag/OpenSeesPy#59]
- [x] Show time instead of frames.

- [x] Investigate saving outputs.

**Comment by cslotboom** [comment]
@u-anurag I noticed that the repeat animation was turned off. Was there any reason for this?
If repeat is turned of, the animation won't restart when the user clicks on the screen.

**Comment by u-anurag** [comment]
I thought it would prevent looping in the video. We can turn it on if it kills the user interaction.

**Comment by cslotboom** [comment]
I think this does kill interactivity - even when the animation is paused, it's looping through frames, so it will get to the final frame then stop iterating.

If the video is looping, maybe we can maybe create a conditional statement and use that to save.
Or we could possibly have a separate command "Save_Animation" - right now none of the other commands save anything.

I'm not sure I'm totally sold on the current interaction. It would be nice to rotate the image without restarting the animation.
We could potentially add a "pause" button. I know the main OpenSees team isn't super keen on GUI elements though.

**Comment by u-anurag** [comment]
I tested it. Repeat=True is not messing up the video. It did happen in an early iteration of the code I tried and I turned it off thinking it might fix the issue. We should go for Repeat=True. You should try the code and see the output.

**Comment by cslotboom** [comment]
So I did try to save a movie, and ended up with a error. I am using QT5 in spyder.

I was under the impression the user needed a FFMpeg writter installed to save the videos, but I'm going to do some more digging and see if I can find a fix that doesn't involve installing one.


![Capture](https://user-images.githubusercontent.com/50510141/87008696-ffcbbd00-c178-11ea-9d56-87985fbe2332.JPG)
![Capture2](https://user-images.githubusercontent.com/50510141/87008711-035f4400-c179-11ea-9270-7ddd06f4c1f4.JPG)
![QT5](https://user-images.githubusercontent.com/50510141/87008722-05c19e00-c179-11ea-8361-3cc3cc5a3ec9.JPG)

**Comment by cslotboom** [comment]
I tried this code from [here](https://matplotlib.org/gallery/animation/basic_example_writer_sgskip.html):
```
Writer = animation.writers['ffmpeg']
writer = Writer(fps=15, metadata=dict(artist='Me'), bitrate=1800)
```

I ended up with a new error:
![Error](https://user-images.githubusercontent.com/50510141/87010250-25f25c80-c17b-11ea-9c05-cfb4a5ca268d.JPG)

It looks like the installation process for Anaconda is fairly straightforward:
`conda install -c conda-forge ffmpeg`

It doesn't seem like a big ask to ask users to install the codex, if they need to output videos.

**Comment by u-anurag** [comment]
Yes, ffmpeg codecs are needed in order to save a movie. The current code works for saving a movie and display animation on my machine.

**Comment by cslotboom** [comment]
If we are looking to document how to do this, I can write up a procedure for including the ffmpeg.

**Comment by u-anurag** [comment]
I am creating a branch for OpenSeesPyDoc to work on documentation. Once I am finished putting the templates for each command, I'll invite you to edit the animation commands.
