### ISSUE TITLE
Create Tests for Plot Functions

### ISSUE THREAD

**Issue by cslotboom** [u-anurag/OpenSeesPy#6]
It would be useful to have a set of test cases that can be used to ensure the plot functions are working correctly. I have some that I can contribute.

**Comment by u-anurag** [comment]
I have models for 2D and 3D beam-column elements, 2D and 3D four-node shell elements, and 3D brick elements that I used to test plotting functions. I'll create a folder and put all the test examples tonight.

**Comment by u-anurag** [comment]
I have added some test examples that I always use to test any changes or addition to plotting functions. I don't have an example for Tri elements yet. If you use them to test animation, add a pushover or time-history analysis to these examples if it is not there already.

**Comment by cslotboom** [comment]
One thing to consider is using Pytest for the plot functions. I have included a few tests that are pytest compatible in a branch I will merge relatively soon.

**Comment by u-anurag** [comment]
OK. That sounds good.
