### ISSUE TITLE
OpenSeesPyDoc Documentation

### ISSUE THREAD

**Issue by u-anurag** [u-anurag/OpenSeesPy#62]
@cslotboom I have put the documentation together. Please check and add more information. Specifically for animation commands. 

https://github.com/u-anurag/OpenSeesPyDoc

**Comment by cslotboom** [comment]
I'll take a look today or tomorrow - in a bit of a crunch right now with work.

**Comment by u-anurag** [comment]
I see the issue was closed. Does it mean that the documentation is good to go?
