### ISSUE TITLE
Consider implementing a 'style' object, to store apperance data

### ISSUE THREAD

**Issue by cslotboom** [u-anurag/OpenSeesPy#7]
Right changing the appearance of objects is a little messy. We pass certain tags to the functions:

e.g.
```
ele_style = {'color':'black', 'linewidth':1, 'linestyle':'-'} # elements
node_style = {'color':'black', 'marker':'o', 'facecolor':'black'} 

def _plotCubeSurf(NodeList, ax, fillSurface, eleStyle)
```

One way to get around this would be to use a single object that stores all relevant style information.
That way we have less variables to keep track of. We could also allow a user to customize the style of their plots.

```
Style.ele_style = {'color':'black', 'linewidth':1, 'linestyle':'-'}
Style.node_style = {'color':'black', 'marker':'o', 'facecolor':'black'} 

def _plotCubeSurf(NodeList, ax, Style)
```

**Comment by u-anurag** [comment]
Let's leave the style within the code for now. We have to add new functions for deformation contours, stress-strain, and force countors. Once we have all the functions, we can group the styles together.

**Comment by cslotboom** [comment]
Okay, let's close for now.
