### ISSUE TITLE
File Structure - Internal vs. external functions

### ISSUE THREAD

**Issue by cslotboom** [u-anurag/OpenSeesPy#8]
Many of the functions in get_rendering, such as _plotCubeSurf(), are not intended to be used by users.

It might be a good idea to keep these in a separate file - the main plotting folder is getting a little busy. On that note, it also might be a good idea to have the database functions in their own file.
Maybe a directory structure as follows makes sense?

get_rendering
internal_plot_functions
internal_database_functions

**Comment by cslotboom** [comment]
in 4cc2855 I contribute some functions to the internal_database_functions. These can be used to get nodes tags/coordinates, and element connectivity. Feel free to remove or make any changes.

**Comment by u-anurag** [comment]
You should work only on the tasks assigned to you. This will prevent us from working on the same task.  I have assigned in the "Issues" tab.

**Comment by u-anurag** [comment]
I guess we are following it now.
