### ISSUE TITLE
Visualization library name

### ISSUE THREAD

**Issue by u-anurag** [u-anurag/OpenSeesPy#82]
This is just a thought. I was thinking of slowly getting rid of `Get_Rendering` and implementing a direct `import openseespy.postprocessing as opsplt` and then `opsplt.plot_model()`. Get_Rendering was my own local file name which got hard to change later. Having a library inside postprocessing gives the impression that multiple libraries can be accommodated. 

This is not a priority and if decided, `Get_Rendering` will fade away over a period of one year. There might be cons of doing this, I don't know.

**Comment by cslotboom** [comment]
I agree, `import openseespy.postprocessing as opsplt` feels much cleaner.
That also might be a good opportunity to make changes that would break existing ifunctions, i.e. clean up some of the function inputs

We should probably pick a release where this happens, and maybe run by Minjie. We can do a soft transition out of Get_Rendering, where Get_Rendering  functions first give a deprecated error, then are eventually removed.

**Comment by u-anurag** [comment]
@zhuminjie do you think it is a good idea? We are not jumping on it right away. This will bring a more object-oriented format to plotting commands.

**Comment by zhuminjie** [comment]
That sounds good. How do you want to do that?

**Comment by u-anurag** [comment]
We'll do that in our fork. `Get_Rendering` will still be available for next release with a message to users "_Starting January 2021, all plotting functions will be imported directly from postprocessing instead of Get_Rendering._" After that date, the program will display a warning "Please use `import openseespy.postprocessing as opsplt` instead" whenever a user tries to import `Get_Rendering` by mistake. 

@cslotboom and I will make sure that the process is smooth, without causing failures to the existing functions.

**Comment by zhuminjie** [comment]
Cool!

**Comment by u-anurag** [comment]
@cslotboom I'll create another milestone and add this task.
