### ISSUE TITLE
Create readODB() command.

### ISSUE THREAD

**Issue by u-anurag** [u-anurag/OpenSeesPy#9]
command to read the output data from ODB folder.

**Comment by cslotboom** [comment]
Hey, so I'm curious, what is the expected output format?

Right now I read all files into a separate variable, so it looks something like this:

`    return nodes, elements, NodeDisp, Reaction, EleForce, EleBasicDef, 
    ElePlasticDef, EleStress, EleStrain`

**Comment by u-anurag** [comment]
See the createODB() command in Get_Rendering.py and let's just start with
displacement and element forces. So we can connect it to existing
plot_deformedshape command and create one plot_elementForces() command.
Once this works, we'll work on stress and strain.

**Comment by cslotboom** [comment]
Okay, I am able to get the other variables, but we can just comment them out for now.
I also have created a test of the  function that works with pytest.

**Comment by cslotboom** [comment]
Hopefully this is addressed in #20.

**Comment by cslotboom** [comment]
Assuming closed in #20.
