### ISSUE TITLE
Get_Rendering.py is not working with local compilation

### ISSUE THREAD

**Issue by JAMMIASHOK** [u-anurag/OpenSeesPy#97]
Hi, Anurag, this is Ashok. Get_Rendering.py is not working with my local compilation. Do you have any suggestions?

**Comment by u-anurag** [comment]
You can just copy the all the files in postprocessing folder to your local compiled directory. That will work.

**Comment by JAMMIASHOK** [comment]
Yes. Thank you. It's working now.
